---
- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/ca_certificate.key

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/certs/certificate.pem
    privatekey_path: /etc/ssl/private/ca_certificate.key
    provider: selfsigned
